Use PimcoreLocationAwareConfigDao
gal-digital-gmbh/pimcore-qrcode-bundle pull request #2
Opened 2022-01-07 14:37 UTC by blankse

2022-01-12 07:53 UTC, blankse commented
@GALCF Can you review this?

2022-01-13 10:51 UTC, GALCF commented
> @GALCF Can you review this?

Looks great, thank you so much!  
I'll add the comments via suggestions in a bit

2022-01-13 10:52 UTC, GALCF requested changes

2022-01-13 10:52 UTC, GALCF commented on src/DependencyInjection/PimcoreQrcodeExtension.php
> +     * @param array $mergedConfig
```suggestion
     * @param array<mixed> $mergedConfig
```

2022-01-13 10:52 UTC, GALCF commented on src/DependencyInjection/PimcoreQrcodeExtension.php
> +     * @param array $mergedConfig
You can run `php vendor/bin/phpstan analyze src --level=8 --memory-limit=-1` to check for static analysis issues

2022-01-13 10:52 UTC, GALCF commented on src/DependencyInjection/PimcoreQrcodeExtension.php
> +            $loader->load('doctrine_migrations.yml');
Could you change the file extension to `.yaml` please

2022-01-13 11:11 UTC, merged